name: Build and Deploy

on:
  push:
    branches:
      - 'master'
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  bundle-addon:
    name: Bundle addon
    runs-on: ubuntu-latest
    container:
      image: debian:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -y
          apt-get install -y zip unzip

      - name: Create addon bundle
        run: |
          zip ClearURLs -r -FS \
            clearurls.js \
            browser-polyfill.js \
            manifest.json \
            img/* \
            external_js/* \
            html/* \
            core_js/* \
            css/* \
            fonts/* \
            _locales/*

      - name: Upload addon artifact
        uses: actions/upload-artifact@v7
        with:
          name: ClearURLs
          path: ClearURLs.zip
          overwrite: 'true'
